### PR TITLE
Octokit

### PR DESCRIPTION
**Pull request by travi**

### CODE REVIEW

**Comment by travi** [comment]
@gr2m anything about this PR that would prevent the WIP bot from reporting success?

**Comment by gr2m** [comment]
Hmm interesting I never saw someone commit wip commits on purpose before, only by accident. Even if the commits are only part of sth bigger you are working on, their should still finish one step towards the bigger goal, that is rather describe then the bigger goal several times? I fear that might be a problem, but it’s easy enough to deploy you very own wip bot and make it work just the way you like it, happy to help with that :)

**Comment by travi** [comment]
the primary reason i use this process is that i prefer continuous integration over feature branches. by using wip commits, i can get commits to `master` sooner while still adhering to [my](https://github.com/travi/commitlint-config-travi/blob/81534d56834d47926f4f5432b5297fb9e7dac012/index.js) commit convention. this PR was a bit out of the ordinary since it was more disruptive.

i eventually want to make greenkeeper-keeper available as a probot service, so it wouldnt be a horrible idea to start by serving an already working one. might not make it happen right away, but its now added to my list. I would recommend updating the description to mention that commits are considered in addition to the PR title.

**Comment by travi** [comment]
also, greenkeeper-keeper is now converted to use octokit and things seem to be working smoothly. i've got some cleanup im planning to do along with some of the breaking changes i have in flight, but its at least in place now. thanks for the tips along the way

**Comment by gr2m** [comment]
We updated the README recently: https://github.com/gr2m/wip-bot#usage

**Comment by travi** [comment]
ah, sure. i guess i was referring to the description [here](https://github.com/apps/wip), since thats what i found by following the "Details" link on the check above

**Comment by gr2m** [comment]
Ha good point, will fix, thanks!

**Comment by travi** [comment]
btw, this is not the first time that our use of `wip` in our "incomplete, but fully production ready, progress toward a feature or fix" commits has run into trouble with similar assumptions to yours. 

we're discussing if we can come up with something that would convey similar meaning for our convention but not collide with this type of assumption (and not be too long).

**Pull request merged**
